name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Clean old build artifacts
        run: |
          rm -rf build/ dist/ *.egg-info

      - name: Install build tools
        run: |
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Check if version exists on PyPI
        id: check-version
        run: |
          PKG_NAME=$(python3 -c "import toml; print(toml.load('pyproject.toml')['project']['name'])")
          PKG_VERSION=$(python3 -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          EXISTS=$(curl -s https://pypi.org/pypi/$PKG_NAME/json | grep -o "\"$PKG_VERSION\"")
          if [ "$EXISTS" != "" ]; then
            echo "Version $PKG_VERSION already exists on PyPI. Skipping upload."
            echo "skip_upload=true" >> $GITHUB_OUTPUT
          else
            echo "skip_upload=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to PyPI
        if: steps.check-version.outputs.skip_upload != 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
